# Generated by Django 3.0.8 on 2020-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to='doctors_pic')),
                ('email', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=20)),
                ('profession', models.CharField(choices=[('Neurologist', 'Neurologist'), ('Gynecologist', 'Gynecologist'), ('Physiologist', 'Physiologist'), ('Orthopedic', 'Orthopedic')], max_length=75)),
            ],
        ),
    ]
