# Generated by Django 3.0.8 on 2020-07-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('related_profession_name', models.CharField(max_length=75)),
                ('department_image', models.ImageField(upload_to='department_pics')),
                ('short_description', models.CharField(max_length=75)),
            ],
        ),
    ]
