# Generated by Django 3.0.6 on 2020-07-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20200719_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor_review',
            name='date',
            field=models.DateField(default='2020-07-20'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
