# Generated by Django 3.0.6 on 2020-07-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20200720_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sender_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patient'),
        ),
        migrations.AlterField(
            model_name='doctor_review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patient'),
        ),
        migrations.AlterField(
            model_name='fakes',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patient'),
        ),
    ]
