# Generated by Django 3.0.6 on 2020-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20200720_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Nothing', max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor_review',
            name='date',
            field=models.DateField(default='2020-07-21'),
        ),
    ]
