# Generated by Django 3.0.6 on 2020-07-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20200721_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Nothing', max_length=15),
        ),
    ]
