# Generated by Django 3.0.8 on 2020-07-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20200721_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_review',
            name='date',
            field=models.DateField(default='2020-07-26'),
        ),
    ]
