# Generated by Django 3.0.8 on 2020-07-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_chats_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='reciver',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='doctor_review',
            name='date',
            field=models.DateField(default='2020-07-27'),
        ),
    ]
